name: Build
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
